# Generated by Django 6.0.3 on 2026-04-03 15:47
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
